///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Sprite Color FX.
// Copyright (c) Ibuprogames. All rights reserved.
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

namespace SpriteColorFX
{
  /// <summary>
  /// This code was automatically generated by 'Color Ramp Tool', do not modify!
  /// </summary>
  public enum SpriteColorRampPalettes
  {
    Fire1 = 0,
    Fire2 = 1,
    Water1 = 2,
    Gem1 = 3,
    Air1 = 4,
    Crystal1 = 5,
    Wood1 = 6,
    Wood2 = 7,
    Stone1 = 8,
    Stone2 = 9,
    Metal1 = 10,
    Metal2 = 11,
  }
}
